### ISSUE TITLE
urllib issue

### ISSUE THREAD

**Issue by nicolepinto** [HSRNetwork/piapi#12]
Hi Guys,

Am I missing something here? (urllib is the new library name for python 3), and imports fine in my notebook. (Note URL, username and pw changed for security)

![urllib](https://user-images.githubusercontent.com/17776264/32308366-a03f189e-bfd9-11e7-8521-623746b47a98.PNG)

**Comment by maximumG** [comment]
Hello Nicole,

Basically you should use the following import statement for it to work.

```
import urllib.parse
```

This is because the *parse* module is embeded inside the *urllib* package.

Would it be possible to make a pull request that will handle python 2 as well as python 3 ?

Thanks.

**Comment by msom** [comment]
Probably fixed with 1e7e9eb0e9f20811b31b5adc804b8a030ef4da8b
