### ISSUE TITLE
Support for v2 requests?

### ISSUE THREAD

**Issue by Jhutterer** [HSRNetwork/piapi#8]
This is more of a feature request.  Is there any plans to incorporate v2 requests, Cisco has made some bigger requests more streamlined in v2.

Let me know if there is anything I can help with, I am subpar programmer, but I am willing to test or information gather as needed.

**Comment by maximumG** [comment]
Glad to hear that some people are using the library :).
I will try to integrate the v2 ressources and services as soon as I get some free time. 

The idea would be not to specify the /v1 or /v2 in the url during the class construction but rather the URL without the /v1 or /v2. It will be up to the library to test both v1 and v2 url.

**Comment by Jhutterer** [comment]
I tried to fork it and make a pull request. I am not sure I did right.
